# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_user2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=120, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('reg_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('user_img', models.FileField(default='author_img/user_normal.jpg', upload_to='author_img', verbose_name='用户图片')),
            ],
            options={
                'verbose_name_plural': 'A1_注册用户2',
                'ordering': ['-reg_time'],
            },
        ),
    ]
