# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reg_user2',
            new_name='Reg_user',
        ),
    ]
