# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0002_auto_20171004_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reg_user',
            options={'ordering': ['-reg_time'], 'verbose_name_plural': 'A1_注册用户'},
        ),
    ]
