# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0003_auto_20171004_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_user',
            name='birthday',
            field=models.DateField(blank=True, default='2000-1-1', verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='reg_user',
            name='mobile_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='手机号码'),
        ),
        migrations.AddField(
            model_name='reg_user',
            name='my_tag',
            field=models.CharField(blank=True, max_length=10, verbose_name='我的标签'),
        ),
        migrations.AddField(
            model_name='reg_user',
            name='self_intro',
            field=models.CharField(blank=True, max_length=100, verbose_name='自我介绍'),
        ),
        migrations.AddField(
            model_name='reg_user',
            name='sex',
            field=models.CharField(blank=True, max_length=2, verbose_name='性别'),
        ),
    ]
